spring:
  cloud:
    gateway:
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS}
            allowedMethods: ${CORS_ALLOWED_METHODS}
            allowedHeaders: ${CORS_ALLOWED_HEADERS}
            allow-credentials: ${CORS_ALLOW_CREDENTIALS}