spring:
  security:
    oauth2:
      client:
        registration:
          passport:
            provider: passport
            client-id: ${IDP_CLIENT_ID:gateway}
            client-secret: ${IDP_CLIENT_SECRET:gateway-secret}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: ${GATEWAY_SERVICE_URL:http://localhost:9000/login/oauth2/code/passport}
            scope:
              - openid
              - profile
        provider:
          passport:
            issuer-uri: ${IDP_ISSUER_URL:http://localhost:8080}
            token-uri: ${IDP_ISSUER_URL:http://localhost:8080}/oauth2/token
            authorization-uri: ${IDP_ISSUER_URL:http://localhost:8080}/oauth2/authorize
            user-info-uri: ${IDP_ISSUER_URL:http://localhost:8080}/userinfo
            jwk-set-uri: ${IDP_ISSUER_URL:http://localhost:8080}/oauth2/jwks
            user-name-attribute: "sub"

      resource-server:
        jwt:
          jwk-set-uri: ${IDP_ISSUER_URL:http://localhost:8080}/oauth2/jwks
