spring:
  security:
    oauth2:
      client:
        registration:
          passport:
            provider: passport
            client-id: ${PASSPORT_CLIENT_ID}
            client-secret: ${PASSPORT_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "${GATEWAY_SERVICE_URL}/login/oauth2/code/passport"
            scope:
              - openid
              - profile
        provider:
          passport:
            issuer-uri: ${PASSPORT_SERVICE_URL}
            token-uri: ${PASSPORT_SERVICE_URL}/oauth2/token
            authorization-uri: ${PASSPORT_SERVICE_URL}/oauth2/authorize
            user-info-uri: ${PASSPORT_SERVICE_URL}/userinfo
            jwk-set-uri: ${PASSPORT_SERVICE_URL}/oauth2/jwks
            user-name-attribute: "sub"

      resourceserver:
        jwt:
          jwk-set-uri: ${PASSPORT_SERVICE_URL}/oauth2/jwks
