spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - Logging=
        - TokenExpired=
        - TokenRelay=
        - ErrorHandling=
      routes:
        # interview backend
        - id: interview-api
          uri: ${INTERVIEW_SERVICE_URL:http://localhost:5043}
          predicates:
            - Path=/interview/**
          filters:
            - RewritePath=/interview/(?<segment>.*),/api/$\{segment}

        # passport backend

        - id: passport-account-api
          uri: ${PASSPORT_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/passport/**
          filters:
            - RewritePath=/passport/(?<segment>.*),/$\{segment}

        # document backend

        - id: document-api
          uri: ${DOCUMENT_SERVICE_URL:http://localhost:3432}
          predicates:
            - Path=/document/**
          filters:
            - RewritePath=/document/(?<segment>.*),/internal/document/s3/$\{segment}

        # document backend

        - id: copilot-api
          uri: ${COPILOT_SERVICE_URL:http://localhost:1343}
          predicates:
            - Path=/copilot/**
          filters:
            - RewritePath=/copilot/(?<segment>.*),/$\{segment}

         # sockets

        - id: socket-interview-room
          uri: ${INTERVIEW_SERVICE_URL:http://localhost:7663}
          predicates:
            - Path=/socket/interview/room/**
          filters:
            - RewritePath=/socket/interview/room/(?<segment>.*),/$\{segment}
