---
spring:
  config:
    activate:
      on-profile: production

gateway.frontend:
  sign-in:
    redirect-query-param: 'redirect-location'
  sign-out:
    redirect-query-param: 'redirect-location'
  security:
    permit-all-patterns:
      - '/login/oauth2/**'
      - '/passport/api/csrf'
      - '/passport/api/accounts/authenticated'

---
spring:
  config:
    activate:
      on-profile: development

gateway.frontend:
  security:
    permit-all-patterns:
      - '/actuator/**'
      - '/passport/api/csrf'
      - '/passport/api/accounts/authenticated'
  sign-in:
    redirect-query-param: 'redirect-location'

  sign-out:
    redirect-query-param: 'redirect-location'