---
spring:
  config:
    activate:
      on-profile: production

  cloud:
    gateway:
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'https://id.sorface.ru'
              - 'https://api.gateway.sorface.ru'
              - 'https://passport.sorface.ru'
              - 'https://interview.sorface.ru'
              - 'https://api.idp.sorface.ru'
            allowedMethods: '*'
            allowedHeaders: '*'
            allow-credentials: true

---
spring:
  config:
    activate:
      on-profile: development

  cloud:
    gateway:
      global-cors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:8080'
              - 'http://localhost:9020'
              - 'http://localhost:9000'
              - 'http://localhost:3000'
              - 'http://localhost:9030'
            allowedMethods: '*'
            allowedHeaders: '*'
            allow-credentials: true
