spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: resource-server
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
  security:
    oauth2:
      client:
        provider:
          passport:
            issuer-uri: http://localhost:8080
            user-name-attribute: sub
        registration:
          passport:
            provider: passport
            client-id: gateway
            client-secret: gateway-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: immediate
  data:
    redis:
      host: localhost
      port: 6380
      
server:
  port: 9000
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    by.sorface.gateway.config.RouteFilterConfig: INFO 