spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: resource-server
          uri: http://localhost:5043
          predicates:
            - Path=/api/**
          filters:
            - RemoveRequestHeader=Cookie
            - RemoveRequestHeader=Set-Cookie
  security:
    oauth2:
      allowed-redirect-hosts:
        - localhost
        - localhost:3000
        - localhost:9020
        - localhost:9030
      query-param-name-redirect-location: redirect-location
      client:
        provider:
          passport:
            issuer-uri: http://localhost:8080
            user-name-attribute: sub
        registration:
          passport:
            provider: passport
            client-id: gateway
            client-secret: gateway-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:9000/login/oauth2/code/passport"
            scope:
              - openid
              - profile
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
  session:
    cookie:
      name: gtw_sid
      domain: localhost
      path: /
      http-only: true
      secure: true
      same-site: Lax
      max-age: 7200
    redis:
      namespace: spring:session
      flush-mode: immediate
      repository-type: indexed
    timeout: 2h
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:testpassword}
      connect-timeout: 5s
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      enabled: true
      correlation:
        enabled: true
    brave:
      enabled: false
    otel:
      enabled: true
      exporter:
        otlp:
          enabled: true
  observations:
    enabled: true
      
server:
  port: 9000
  
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive: TRACE
    by.sorface.gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.session: DEBUG