server:
  port: ${APPLICATION_TARGET_PORT:9000}

application:
  metadata:
    version: ${APPLICATION_METADATA_VERSION:1.0.0}

spring:
  application:
    name: gateway
  banner:
    charset: UTF-8
    location: classpath:banner.txt

  config:
    import:
      - classpath:imports/gateway.cors.yml
      - classpath:imports/gateway.session.yml
      - classpath:imports/gateway.datasource.yml
      - classpath:imports/gateway.route.yml
      - classpath:imports/gateway.security.yml
      - classpath:imports/gateway.frontend.yml

logging:
  level:
    root: info
    org:
      springframework:
        web:
          reactive: error
          filter: error
          cors: warn
        security: error
        cloud:
          gateway: info
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} %highlight(%-5level) [%blue(%X{traceId:-})|%green(%X{spanId})] [%thread] %magenta([%file:%line]) : %msg%n'

---

# docker profile configuration

spring:
  config:
    activate:
      on-profile: development

  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

management:
  endpoints:
    enabled-by-default: true

logging:
  level:
    root: trace
    reactor:
      netty: trace
    org:
      springframework:
        web:
          reactive: trace
          filter: trace
          cors: trace
        security: trace
        cloud:
          gateway: trace
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} %highlight(%-5level) [%blue(%X{traceId:-})|%green(%X{spanId})] [%thread] %magenta([%file:%line]) : %msg%n'
